project_id = "sumyeaysdumzyaqdsyjd"

[auth]
enabled = true
site_url = "https://restaurant.arunkhadka.com"
additional_redirect_urls = [
  "https://restaurant.arunkhadka.com",
  "http://localhost:5173"
]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_manual_linking = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.external.github]
enabled = false
client_id = ""
secret = ""

[storage]
file_size_limit = "50MiB"

[functions.create-stripe-payment]
verify_jwt = false

[functions.verify-stripe-payment]
verify_jwt = false

[functions.refund-stripe-payment]
verify_jwt = false

[functions.send-order-email]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.store-push-subscription]
verify_jwt = false

[functions.check-user-exists]
verify_jwt = false

[functions.delete-user-account]
verify_jwt = false

[functions.charge-stripe-additional]
verify_jwt = false

[functions.send-substitution-email]
verify_jwt = false
